version: "3"

services:
  redis-service: 
    container_name: redis-service
    image: redis
    ports:
      - "6379:6379"
  mongo-service: 
    container_name: mongo-service
    image: mongo
    ports:
      - "27017:27017"

  auth-service:
    container_name: auth-service
    build: ./auth-service
    restart: always
    ports:
      - "8001:8008"
    depends_on:
      - redis-service
      - mongo-service
    environment:
      - PORT=8008
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379
      - MONGODB_URL=mongodb://mongo-service:27017/micro-auth
