version: "3"

services:
  redis-service: 
    container_name: redis-service
    image: redis
    ports:
      - "6379:6379"
  mongo-service: 
    container_name: mongo-service
    image: mongo
    ports:
      - "27017:27017"

  api-getaway: 
    container_name: nginx
    image: nginx
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - post-service
      - comment-service
    volumes:
      - ./api-getaway/nginx.conf:/etc/nginx/nginx.conf:ro

  auth-service:
    container_name: auth-service
    build: ./auth-service
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - redis-service
      - mongo-service
    environment:
      - PORT=8081
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379
      - MONGODB_URL=mongodb://mongo-service:27017/micro-auth

  post-service:
    container_name: post-service
    build: ./post-service
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - redis-service
      - mongo-service
      - auth-service
    environment:
      - PORT=8082
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379
      - MONGODB_URL=mongodb://mongo-service:27017/micro-posts
      - AUTH_SERVICE_BASE_URL=http://auth-service:8081

  comment-service:
    container_name: comment-service
    build: ./comment-service
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - redis-service
      - mongo-service
      - auth-service
    environment:
      - PORT=8083
      - REDIS_HOST=redis-service
      - REDIS_PORT=6379
      - MONGODB_URL=mongodb://mongo-service:27017/micro-comments
      - AUTH_SERVICE_BASE_URL=http://auth-service:8081
